name: Test Job
on:
  push:
    branches: [main]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Does it reach up to here
        run: echo "Okay, catch it, Someone pushed"

  Deploy:
    runs-on: ubuntu-latest
    needs: Test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        echo "${{ secrets.IMROSHAN_AUTHKEY_VRG }}" >> imroshan_authkey_vrg.pem
        chmod 600 imroshan_authkey_vrg.pem
    - name: Copy files to EC2 instance
      run: |
            scp -i imroshan_authkey_vrg.pem \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            -r ./* ubuntu@54.157.237.164:/home/ubuntu
    - name: Install Apache on Server
      run: |
          ssh -o StrictHostKeyChecking=no -i imroshan_authkey_vrg.pem ubuntu@54.157.237.164 'sudo apt-get install -y apache2 '
    - name: Install MariaDB
      run: |
          ssh -o StrictHostKeyChecking=no -i imroshan_authkey_vrg.pem ubuntu@54.157.237.164 'sudo apt-get update -y && sudo apt-get install mariadb-server -y'

    - name: Configure MariaDB
      run: |
        ssh -o StrictHostKeyChecking=no -i imroshan_authkey_vrg.pem ubuntu@54.157.237.164 'sudo mariadb -e "UPDATE mysql.user SET Password = PASSWORD('\'ugra3194\'') WHERE User = '\'root\''"'
        ssh -o StrictHostKeyChecking=no -i imroshan_authkey_vrg.pem ubuntu@54.157.237.164 'sudo mariadb -e "DELETE FROM mysql.user WHERE User='\''root'\'' AND Host NOT IN ('\''localhost'\'', '\''127.0.0.1'\'', '\''::1'\'')"'
        ssh -o StrictHostKeyChecking=no -i imroshan_authkey_vrg.pem ubuntu@54.157.237.164 'sudo mariadb -e "DELETE FROM mysql.user WHERE User=''\''"'
        ssh -o StrictHostKeyChecking=no -i imroshan_authkey_vrg.pem ubuntu@54.157.237.164 'sudo mariadb -e "DELETE FROM mysql.db WHERE Db='\''test'\'' OR Db='\''test\\_%'\''"'
        ssh -o StrictHostKeyChecking=no -i imroshan_authkey_vrg.pem ubuntu@54.157.237.164 'sudo mariadb -e "FLUSH PRIVILEGES"'

    - name: Start MySQL service
      run: |
          ssh -o StrictHostKeyChecking=no -i imroshan_authkey_vrg.pem ubuntu@54.157.237.164 'sudo systemctl start mysql'
          
    - name: Create MySQL Database
      run: |
        ssh -o StrictHostKeyChecking=no -i imroshan_authkey_vrg.pem ubuntu@54.157.237.164 'mysql -h 54.157.237.164 -u root - ugra3194 -e "CREATE DATABASE chatapp;" '


