name: Test Job
on:
  push:
    branches: [main]
jobs:
  Hello:
    runs-on: ubuntu-latest
    steps:
      - name: Does it reach up to here
        run: echo "Okay, catch it, Someone pushed"

  SSH_Setup:
    runs-on: ubuntu-latest
    needs: Hello
    steps:
      - name: Setup SSH key
        run: |
          echo "${{ secrets.IMROSHAN_AUTHKEY_VRG }}" > imroshan_authkey_vrg.pem
          chmod 400 imroshan_authkey_vrg.pem
  SSH-ing:
    runs-on: ubuntu-latest
    needs: SSH_Setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy file to EC2 instance
        run: |
          echo "$SSH_PRIVATE_KEY" > imroshan_authkey_vrg.pem
          chmod 400 imroshan_authkey_vrg.pem
          sudo scp -i imroshan_authkey_vrg.pem \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            -r ./* ubuntu@18.212.85.125:/home/ubuntu/
