name: Test Job

on:
  push:
    branches: [main]

jobs:

  Hello:
    runs-on: ubuntu-latest
    steps:
      - name: Does it reach up to here
        run: echo "Okay, catch it, Someone pushed"


  SSH_Setup:
    runs-on: ubuntu-latest
    steps:
      - name: SSH
        run: |
          echo "${{secrets.IMROSHAN_AUTHKEY_VRG}}" >> imroshan_authkey_vrg.pem
          chmod 400 imroshan_authkey_vrg.pem
  SSH-ing:
    runs-on: ubuntu-latest
    needs: SSH_Setup

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy file to EC2 instance
      run: |
        scp -i imroshan_authkey_vrg.pem \
        -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null \
        -r ./* ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_IP_ADDRESS }}:/home/ubuntu/app/
