name: Test Job
on:
  push:
    branches: [main]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Does it reach up to here
        run: echo "Okay, catch it, Someone pushed"

  Deploy:
    runs-on: ubuntu-latest
    needs: Test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Apache on Server
      run: |
          sudo apt-get install -y apache2 
    - name: Install MariaDB
      run: |
          sudo apt-get update -y && sudo apt-get install mariadb-server -y


    - name: Configure MySQL
      run: |
          sudo mysql_secure_installation <<EOF
          Y
          ugra3194
          ugra3194
          Y
          Y
          Y
          Y
          EOF
