name: Test Job

on:
  push:
    branches: [main]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello On Push
        run: echo "Hello, Who is there to push on my Repository"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Somebody Push
        run: echo "Let me know who performed the Push Event"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with: 
          php-version: 8.2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install PHP dependency Manager
        uses: ramsey/composer-install@v2
  Hello:
    runs-on: ubuntu-latest
    steps:
      - name: Does it reach up to here?
        run: echo "Okie Catch it"
