name: Install and Configure MySQL

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server


      - name: Root Password
        run: |
          ' sudo mysql
          ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';
          exit'


#       - name: Configure MySQL
#         run: |
#           sudo mysql_secure_installation <<EOF
          
#           Y
#           your_root_password
#           your_root_password
#           Y
#           Y
#           Y
#           Y
#           EOF
