name: Test Job
on:
  push:
    branches: [main]
jobs:
  Hello:
    runs-on: ubuntu-latest
    steps:
      - name: Does it reach up to here
        run: echo "Okay, catch it, Someone pushed"

  SSH_Setup:
    runs-on: ubuntu-latest
    needs: Hello
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        echo "${{ secrets.IMROSHAN_AUTHKEY_VRG }}" >> imroshan_authkey_vrg.pem
        chmod 600 imroshan_authkey_vrg.pem

    - name: Copy files to EC2 instance
      run: |
            scp -i imroshan_authkey_vrg.pem \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            -r ./* ubuntu@54.157.237.164:/home/ubuntu
